name: deploy-api-go
on:
  workflow_run:
    workflows: ["build-api-go"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy API Go
        run: |
          echo "todo"